# Generated by Django 4.2.6 on 2023-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='menu_name',
            field=models.CharField(default='main_menu', max_length=100),
        ),
    ]
